//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptaUnaPatita.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascota()
        {
            this.MascotaSolicitud = new HashSet<MascotaSolicitud>();
            this.MascotaUsuario = new HashSet<MascotaUsuario>();
        }
    
        public int Id { get; set; }
        public int IdTipoAnimal { get; set; }
        public int IdSexo { get; set; }
        public int IdTamanio { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Raza { get; set; }
        public string Detalle { get; set; }
    
        public virtual Sexo Sexo { get; set; }
        public virtual Tamanio Tamanio { get; set; }
        public virtual TipoAnimal TipoAnimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MascotaSolicitud> MascotaSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MascotaUsuario> MascotaUsuario { get; set; }
    }
}
