//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptaUnaPatita.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MascotaSolicitud
    {
        public int Id { get; set; }
        public int IdMascota { get; set; }
        public int IDSolicitud { get; set; }
    
        public virtual Mascota Mascota { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
