//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptaUnaPatita.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.MascotaSolicitud = new HashSet<MascotaSolicitud>();
        }
    
        public int Id { get; set; }
        public int IdSolicitante { get; set; }
        public int IdColaborador { get; set; }
        public string Numero { get; set; }
        public string Razon { get; set; }
        public bool AceptoTerminos { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        public virtual Entidad Entidad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MascotaSolicitud> MascotaSolicitud { get; set; }
    }
}
