//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptaUnaPatita.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.EntidadUsuario = new HashSet<EntidadUsuario>();
            this.MascotaUsuario = new HashSet<MascotaUsuario>();
        }

        public int Id { get; set; }
        public Nullable<int> IdRol { get; set; }
        [Required(ErrorMessage = "El nombre es Necesario")]
        public string Nombre { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "La contraseña es Necesaria")]
        public string Contrasenia { get; set; }
    
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntidadUsuario> EntidadUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MascotaUsuario> MascotaUsuario { get; set; }
    }
}
